name: Auto build config image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build config image
    if: startswith(github.event.comment.body, '/imagebuild_configs')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - registry: docker.io
            username: ${{ github.repository_owner }}
            repo: ${{ github.repository_owner }}
            password: ${{ secrets.REGISTRY }}
          - registry: registry.cn-qingdao.aliyuncs.com
            username: ${{ secrets.ALIY_REGISTRY_NAME }}
            repo: ${{ github.repository_owner }}
            password: ${{ secrets.ALIY_REGISTRY_PASSWD }}
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - name: Auto build image
        id: autobuild
        env:
          ak: ${{ secrets.AK }}
          sk: ${{ secrets.SK }}
          sealos: 4.1.0-rc1
        run: |
          commentbody="${{github.event.comment.body}}"
          app=`echo "$commentbody"| awk '{print $2}'`
          version=`echo "$commentbody"| awk '{print $3}'`
          wget https://github.com/labring/sealos/releases/download/v$sealos/sealos_${sealos}_linux_amd64.tar.gz
          tar -zxvf sealos_${sealos}_linux_amd64.tar.gz sealos
          chmod a+x sealos
          sudo mv sealos /usr/bin/
          wget https://github.com/labring/cluster-image/releases/download/depend/buildah.linux.amd64 --no-check-certificate -O buildah && chmod a+x buildah
          sudo mv buildah /usr/bin/
          cd config/$app/$version
          filename=Kubefile
          if  [ -f Dockerfile ]; then
            filename=Dockerfile
          fi
          sudo sealos login ${{ matrix.registry }}  -u ${{ matrix.username }} -p ${{ matrix.password }} 
          sudo sealos build -t ${{ matrix.registry }}/${{ matrix.repo }}/$app:$version -f $filename .   
          sudo sealos push ${{ matrix.registry }}/${{ matrix.repo }}/$app:$version
      - name: Success Commit
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ```
            image docker.io/labring/$app:$version build successfully!
            image registry.cn-qingdao.aliyuncs.com/labring/$app:$version build successfully!
            ```

            detail log please view [autobuild-configs](https://github.com/labring/cluster-image/actions/workflows/autobuild-configs.yml)
