name: Auto build image k8s for part4
on:
  workflow_dispatch:
    inputs:
      sealosPatch:
        description: 'sealos patch image for development.'
        required: false
        default: ghcr.io/labring/sealos-patch:dev
jobs:
  install-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auto install k8s using sealos
        uses: labring/sealos-action@v0.0.1
        with:
          image: labring/kubernetes:v1.24.0
          sealosVersion: 4.1.3
          buildah: false
          debug: true
