name: Auto build APP image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build app image
    if: startswith(github.event.comment.body, '/imagebuild_apps')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - name: Auto build image
        id: autobuild
        env:
          ak: ${{ secrets.AK }}
          sk: ${{ secrets.SK }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY }}
        run: |
          commentbody="${{github.event.comment.body}}"
          app=`echo "$commentbody"| awk '{print $2}'`
          version=`echo "$commentbody"| awk '{print $3}'`
          subpath=`echo "$commentbody"| awk '{print $4}'`
          wget https://github.com/labring/sealos/releases/download/v$sealos/sealos_${sealos}_linux_amd64.tar.gz
          tar -zxvf sealos_${sealos}_linux_amd64.tar.gz
          chmod a+x sealos
          sudo mv sealos /usr/bin/
          wget https://sealyun-home.oss-accelerate.aliyuncs.com/images/buildah.linux.amd64 --no-check-certificate -O buildah && chmod a+x buildah
          sudo mv buildah /usr/bin/
          cd runtime/config/$app
          filename=Kubefile
          if  [ -f Dockerfile ]; then
            filename=Dockerfile
          fi
          sudo sealos login $registry -u $username -p $password
          cp -rf $subpath $subpath-amd64
          cp -rf $subpath $subpath-arm64
          cd $subpath-amd64 && sh init.sh amd64
          sudo sealos build -t $registry/$username/$app:$version-amd64 --platform linux/amd64  -f $filename .  >  ../output.log && cd ../
          cd $subpath-arm64 && sh init.sh arm64
          sudo sealos build -t $registry/$username/$app:$version-arm64 --platform linux/arm64  -f $filename .  >> ../output.log && cd ../
          sudo buildah push $registry/$username/$app:$version-amd64
          sudo buildah push $registry/$username/$app:$version-arm64
          sudo buildah manifest create $registry/$username/$app:$version
          sudo buildah manifest add $registry/$username/$app:$version docker://$registry/$username/$app:$version-amd64
          sudo buildah manifest add $registry/$username/$app:$version docker://$registry/$username/$app:$version-arm64
          sudo buildah manifest push --all $registry/$username/$app:$version docker://$registry/$username/$app:$version
          echo "sealos push $registry/$username/$app:$version success"
          body="$(cat output.log)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Success Commit
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ```
            ${{ steps.autobuild.outputs.body }}
            ```

            detail log please view [autobuild-apps](https://github.com/labring/cluster-image/actions/workflows/autobuild-apps.yml)
