name: Auto build image schedule
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#  schedule:
#    - cron: '0 22 * * *'
jobs:
  resolve-issue-sealoslatest:
    runs-on: ubuntu-latest
    outputs:
      sealoslatest: ${{ steps.set-sealoslatest.outputs.sealoslatest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set sealos LatestVersion
        id: set-sealoslatest
        run: |
          export commentbody="${{github.event.comment.body}}"
          .github/scripts/versions_sealos_default.sh
  resolve-versions-arch:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-versions.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Resolve Versions
        id: set-versions
        run: .github/scripts/versions_schedule_arch.sh
  resolve-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-versions.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Resolve Versions
        id: set-versions
        run: .github/scripts/versions_schedule.sh
  build-images:
    name: Auto build schedule app image
    env:
      sealoslatest: ${{ needs.resolve-issue-sealoslatest.outputs.sealoslatest }}
    needs:
      - resolve-versions-arch
      - resolve-issue-sealoslatest
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.resolve-versions-arch.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download buildah and sealos
        run: .github/scripts/download.sh

      - name: Auto build image
        env:
          registry: docker.io
          username: ${{ github.repository_owner }}
          repo: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY }}
          arch: ${{ matrix.arch }}
          app: ${{ matrix.app }}
          version: ${{ matrix.version }}
        run: .github/scripts/apps.sh

  build_manifest:
    needs:
      - resolve-versions
      - build-images
      - resolve-issue-sealoslatest
    env:
      sealoslatest: ${{ needs.resolve-issue-sealoslatest.outputs.sealoslatest }}
    name: Auto manifest schedule app image
    strategy:
      matrix: ${{ fromJson(needs.resolve-versions.outputs.matrix) }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download buildah and sealos
        run: .github/scripts/download.sh
      - name: Manifest Image
        env:
          registry: docker.io
          username: ${{ github.repository_owner }}
          repo: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY }}
          app: ${{ matrix.app }}
          version: ${{ matrix.version }}
        run: .github/scripts/manifest-other.sh
