name: Auto build image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build k8s image
    if: startswith(github.event.comment.body, '/imagebuild_k8s')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Build
        run: go env -w GOOS=linux && go env -w GOARCH=amd64 && go env -w  GOPROXY=https://goproxy.io  && go build -o cluster-image -v && chmod a+x cluster-image

      - name: Auto build image
        id: autobuild
        env:
          ak: ${{ secrets.AK }}
          sk: ${{ secrets.SK }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY }}
        run: |
          commentbody="${{github.event.comment.body}}"
          version=`echo "$commentbody"|cut -d" " -f2`
          echo "start to build kubernetes:$version"
          export PATH=${PATH}:$(pwd)
          cluster-image run --ak ${ak} --sk ${sk} --repo-domain ${registry} --repo-password ${password} --repo-username ${username} --repo ${username} --k8s-versions $version --logger-file output.log
          body="$(cat output.log)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Success Commit
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ```
            ${{ steps.autobuild.outputs.body }}
            ```
