name: Auto build APP image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build app image
    if: startswith(github.event.comment.body, '/imagebuild_apps')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Auto build image
        id: autobuild
        env:
          ak: ${{ secrets.AK }}
          sk: ${{ secrets.SK }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY }}
        run: |
          DOWNLOAD_URL=$(curl -LsSf https://api.github.com/repos/labring/cluster-image/releases/latest | jq -r ".assets[0].browser_download_url")
          wget -c $DOWNLOAD_URL -O cluster-image && chmod +x cluster-image
          export PATH=${PATH}:$(pwd)
          commentbody="${{github.event.comment.body}}"
          app=`echo "$commentbody"| awk '{print $2}'`
          version=`echo "$commentbody"| awk '{print $3}'`
          subpath=`echo "$commentbody"| awk '{print $4}'`
          cluster-image application --ak ${ak} --sk ${sk} --repo-domain ${registry} --repo-password ${password} --repo-username ${username} --repo ${username} --type ${app}  --version ${version} --dir ${subpath} --logger-file output.log
          body="$(cat output.log)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Success Commit
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ```
            ${{ steps.autobuild.outputs.body }}
            ```

            detail log please view [autobuild-apps](https://github.com/labring/cluster-image/actions/workflows/autobuild-apps.yml)
