name: Auto build APP image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build app image
    if: startswith(github.event.comment.body, '/imagebuild_apps')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - name: Auto build image
        id: autobuild
        env:
          ak: ${{ secrets.AK }}
          sk: ${{ secrets.SK }}
          registry: docker.io
          username: ${{ github.repository_owner }}
          repo: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY }}
          sealos: 4.0.0-rc1
          aliyun_registry: registry.cn-qingdao.aliyuncs.com
          aliyun_username: ${{ secrets.ALIY_REGISTRY_NAME }}
          aliyun_repo: ${{ github.repository_owner }}
          aliyun_password: ${{ secrets.ALIY_REGISTRY_PASSWD }}
        run: |
          commentbody="${{github.event.comment.body}}"
          app=`echo "$commentbody"| awk '{print $2}'`
          version=`echo "$commentbody"| awk '{print $3}'`
          echo "app: $app"
          echo "version: $version"
          wget https://github.com/labring/sealos/releases/download/v$sealos/sealos_${sealos}_linux_amd64.tar.gz
          tar -zxvf sealos_${sealos}_linux_amd64.tar.gz
          chmod a+x sealos
          sudo mv sealos /usr/bin/
          wget https://sealyun-home.oss-accelerate.aliyuncs.com/images/buildah.linux.amd64 --no-check-certificate -O buildah
          chmod a+x buildah
          sudo mv buildah /usr/bin/
          cp -rf hack/* .
          sudo sh application.sh $version $registry $repo $username $password $app  > output.log
          sudo sh application.sh $version $aliyun_registry $aliyun_repo $aliyun_username $aliyun_password $app
          echo "sealos push $aliyun_registry/$aliyun_repo/$app:$version success" >> output.log

          body="$(cat output.log)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Success Commit
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ```
            ${{ steps.autobuild.outputs.body }}
            ```

            detail log please view [autobuild-apps](https://github.com/labring/cluster-image/actions/workflows/autobuild-apps.yml)
