name: Auto test for sealos action
on:
  workflow_dispatch:
    inputs:
      sealosPatch:
        description: 'sealos patch image for development.'
        required: false
        default: ghcr.io/labring/sealos-patch:dev
jobs:
  install-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trace memory
        run: |
          env
          cd /home/runner/work && tree -L 5
          free -m
      - name: Auto install sealos
        uses: labring/sealos-action@v0.0.2-rc1
        with:
          sealosVersion: 4.1.3
          buildah: false
          debug: true
          sealctl: true
      - name: Auto install k8s using sealos
        uses: labring/sealos-action@v0.0.2-rc1
        with:
          type: version
      - name: Login sealos
        uses: labring/sealos-action@v0.0.2-rc1
        with:
          type: login
          username: labring
          password: ${{ secrets.REGISTRY }}
          registry: docker.io
      - name: Build sealos image by dockerfile
        uses: labring/sealos-action@v0.0.2-rc1
        with:
          type: build
          image: ghcr.io/${{ github.repository_owner }}/testactionimage:dockerfile
          debug: true
          working-directory: test/build-dockerfile
      - name: Build sealos image by kubefile
        uses: labring/sealos-action@v0.0.2-rc1
        with:
          type: build
          image: ghcr.io/${{ github.repository_owner }}/testactionimage:kubefile
          debug: true
          working-directory: test/build-kubefile
      - name: Run images
        uses: labring/sealos-action@v0.0.2-rc1
        with:
          type: images
          debug: true
#      - name: Auto install k8s using sealos
#        uses: labring/sealos-action@v0.0.2-rc3
#        with:
#          image: labring/kubernetes:v1.24.0
#          sealosVersion: 4.1.3
#          buildah: false
#          debug: true
